services:
  - name: order-service-a
    type: web
    runtime: node
    plan: free
    rootDir: services/order-service
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    buildFilter:
      paths:
        - services/order-service/**
    envVars:
      - key: REPLICA_ID
        value: a
      - key: INVENTORY_URL
        value: https://inventory-service-gvzo.onrender.com
      - key: NOTIFICATION_URL
        value: https://notification-service-qu9y.onrender.com
      - key: CHAOS_SECRET
        sync: false

  - name: order-service-b
    type: web
    runtime: node
    plan: free
    rootDir: services/order-service
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    buildFilter:
      paths:
        - services/order-service/**
    envVars:
      - key: REPLICA_ID
        value: b
      - key: INVENTORY_URL
        value: https://inventory-service-gvzo.onrender.com
      - key: NOTIFICATION_URL
        value: https://notification-service-qu9y.onrender.com
      - key: CHAOS_SECRET
        sync: false

  - name: inventory-service
    type: web
    runtime: node
    plan: free
    rootDir: services/inventory-service
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    buildFilter:
      paths:
        - services/inventory-service/**
    envVars:
      - key: CHAOS_SECRET
        sync: false

  - name: notification-service
    type: web
    runtime: node
    plan: free
    rootDir: services/notification-service
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    buildFilter:
      paths:
        - services/notification-service/**
    envVars:
      - key: CHAOS_SECRET
        sync: false

  - name: control-plane
    type: web
    runtime: node
    plan: free
    rootDir: services/control-plane
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    buildFilter:
      paths:
        - services/control-plane/**
    envVars:
      - key: ORDER_A_URL
        value: https://order-service-a.onrender.com
      - key: ORDER_B_URL
        value: https://order-service-b-vi4q.onrender.com
      - key: INVENTORY_URL
        value: https://inventory-service-gvzo.onrender.com
      - key: NOTIFICATION_URL
        value: https://notification-service-qu9y.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: RENDER_API_KEY
        sync: false
      - key: RENDER_SERVICE_IDS
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: CHAOS_SECRET
        sync: false
      - key: DASHBOARD_ORIGIN
        sync: false
      - key: ADMIN_SECRET
        sync: false
